name: DimensionControl
version: 1.0
main: me.maxgim234.dimensioncontrol.DimensionControl
description: Control access to dimensions with bypass permissions.
api-version: 1.21

commands:
  end:
    description: Open/close the End dimension
    usage: /end <open|close|status>
  nether:
    description: Open/close the Nether dimension
    usage: /nether <open|close|status>

permissions:
  dimensioncontrol.admin:
    description: Gives access to all DimensionControl commands
    default: op
  dimensioncontrol.bypass:
    description: Bypass all dimension restrictions
    default: op
  dimensioncontrol.bypass.end:
    description: Bypass End restrictions
    default: false
  dimensioncontrol.bypass.nether:
    description: Bypass Nether restrictions
    default: false